behaviors:
  MoveToGoal:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 3.0e-4
      beta: 5.0e-3
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 8
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
    reward_signals:
      extrinsic:
        strength: 1
        gamma: 0.99
      curiosity:
        strength: 0.1
        gamma: 0.99
    max_steps: 10000000000000
    time_horizon: 64
    summary_freq: 20000